namespace Elmah.Io.HResults.Facilities
{
    internal class FacilityComplusResolver : FacilityResolverBase
    {
        public FacilityComplusResolver() : base(17, "FACILITY_COMPLUS")
        {
        }

        internal override Code Resolve(bool failure, int code)
        {
            return code switch
            {
                1025 => new Code(code, "COMADMIN_E_OBJECTERRORS", "Errors occurred accessing one or more objects—the ErrorInfo collection contains more detail."),
                1026 => new Code(code, "COMADMIN_E_OBJECTINVALID", "One or more of the object's properties are missing or invalid."),
                1027 => new Code(code, "COMADMIN_E_KEYMISSING", "The object was not found in the catalog."),
                1028 => new Code(code, "COMADMIN_E_ALREADYINSTALLED", "The object is already registered."),
                1031 => new Code(code, "COMADMIN_E_APP_FILE_WRITEFAIL", "An error occurred writing to the application file."),
                1032 => new Code(code, "COMADMIN_E_APP_FILE_READFAIL", "An error occurred reading the application file."),
                1033 => new Code(code, "COMADMIN_E_APP_FILE_VERSION", "Invalid version number in application file."),
                1034 => new Code(code, "COMADMIN_E_BADPATH", "The file path is invalid."),
                1035 => new Code(code, "COMADMIN_E_APPLICATIONEXISTS", "The application is already installed."),
                1036 => new Code(code, "COMADMIN_E_ROLEEXISTS", "The role already exists."),
                1037 => new Code(code, "COMADMIN_E_CANTCOPYFILE", "An error occurred copying the file."),
                1039 => new Code(code, "COMADMIN_E_NOUSER", "One or more users are not valid."),
                1040 => new Code(code, "COMADMIN_E_INVALIDUSERIDS", "One or more users in the application file are not valid."),
                1041 => new Code(code, "COMADMIN_E_NOREGISTRYCLSID", "The component's CLSID is missing or corrupt."),
                1042 => new Code(code, "COMADMIN_E_BADREGISTRYPROGID", "The component's programmatic ID is missing or corrupt."),
                1043 => new Code(code, "COMADMIN_E_AUTHENTICATIONLEVEL", "Unable to set required authentication level for update request."),
                1044 => new Code(code, "COMADMIN_E_USERPASSWDNOTVALID", "The identity or password set on the application is not valid."),
                1048 => new Code(code, "COMADMIN_E_CLSIDORIIDMISMATCH", "Application file CLSIDs or instance identifiers (IIDs) do not match corresponding DLLs."),
                1049 => new Code(code, "COMADMIN_E_REMOTEINTERFACE", "Interface information is either missing or changed."),
                1050 => new Code(code, "COMADMIN_E_DLLREGISTERSERVER", "DllRegisterServer failed on component install."),
                1051 => new Code(code, "COMADMIN_E_NOSERVERSHARE", "No server file share available."),
                1053 => new Code(code, "COMADMIN_E_DLLLOADFAILED", "DLL could not be loaded."),
                1054 => new Code(code, "COMADMIN_E_BADREGISTRYLIBID", "The registered TypeLib ID is not valid."),
                1055 => new Code(code, "COMADMIN_E_APPDIRNOTFOUND", "Application install directory not found."),
                1059 => new Code(code, "COMADMIN_E_REGISTRARFAILED", "Errors occurred while in the component registrar."),
                1060 => new Code(code, "COMADMIN_E_COMPFILE_DOESNOTEXIST", "The file does not exist."),
                1061 => new Code(code, "COMADMIN_E_COMPFILE_LOADDLLFAIL", "The DLL could not be loaded."),
                1062 => new Code(code, "COMADMIN_E_COMPFILE_GETCLASSOBJ", "GetClassObject failed in the DLL."),
                1063 => new Code(code, "COMADMIN_E_COMPFILE_CLASSNOTAVAIL", "The DLL does not support the components listed in the TypeLib."),
                1064 => new Code(code, "COMADMIN_E_COMPFILE_BADTLB", "The TypeLib could not be loaded."),
                1065 => new Code(code, "COMADMIN_E_COMPFILE_NOTINSTALLABLE", "The file does not contain components or component information."),
                1066 => new Code(code, "COMADMIN_E_NOTCHANGEABLE", "Changes to this object and its subobjects have been disabled."),
                1067 => new Code(code, "COMADMIN_E_NOTDELETEABLE", "The delete function has been disabled for this object."),
                1068 => new Code(code, "COMADMIN_E_SESSION", "The server catalog version is not supported."),
                1069 => new Code(code, "COMADMIN_E_COMP_MOVE_LOCKED", "The component move was disallowed because the source or destination application is either a system application or currently locked against changes."),
                1070 => new Code(code, "COMADMIN_E_COMP_MOVE_BAD_DEST", "The component move failed because the destination application no longer exists."),
                1072 => new Code(code, "COMADMIN_E_REGISTERTLB", "The system was unable to register the TypeLib."),
                1075 => new Code(code, "COMADMIN_E_SYSTEMAPP", "This operation cannot be performed on the system application."),
                1076 => new Code(code, "COMADMIN_E_COMPFILE_NOREGISTRAR", "The component registrar referenced in this file is not available."),
                1077 => new Code(code, "COMADMIN_E_COREQCOMPINSTALLED", "A component in the same DLL is already installed."),
                1078 => new Code(code, "COMADMIN_E_SERVICENOTINSTALLED", "The service is not installed."),
                1079 => new Code(code, "COMADMIN_E_PROPERTYSAVEFAILED", "One or more property settings are either invalid or in conflict with each other."),
                1080 => new Code(code, "COMADMIN_E_OBJECTEXISTS", "The object you are attempting to add or rename already exists."),
                1081 => new Code(code, "COMADMIN_E_COMPONENTEXISTS", "The component already exists."),
                1083 => new Code(code, "COMADMIN_E_REGFILE_CORRUPT", "The registration file is corrupt."),
                1084 => new Code(code, "COMADMIN_E_PROPERTY_OVERFLOW", "The property value is too large."),
                1086 => new Code(code, "COMADMIN_E_NOTINREGISTRY", "Object was not found in registry."),
                1087 => new Code(code, "COMADMIN_E_OBJECTNOTPOOLABLE", "This object cannot be pooled."),
                1094 => new Code(code, "COMADMIN_E_APPLID_MATCHES_CLSID", "A CLSID with the same GUID as the new application ID is already installed on this machine."),
                1095 => new Code(code, "COMADMIN_E_ROLE_DOES_NOT_EXIST", "A role assigned to a component, interface, or method did not exist in the application."),
                1096 => new Code(code, "COMADMIN_E_START_APP_NEEDS_COMPONENTS", "You must have components in an application to start the application."),
                1097 => new Code(code, "COMADMIN_E_REQUIRES_DIFFERENT_PLATFORM", "This operation is not enabled on this platform."),
                1098 => new Code(code, "COMADMIN_E_CAN_NOT_EXPORT_APP_PROXY", "Application proxy is not exportable."),
                1099 => new Code(code, "COMADMIN_E_CAN_NOT_START_APP", "Failed to start application because it is either a library application or an application proxy."),
                1100 => new Code(code, "COMADMIN_E_CAN_NOT_EXPORT_SYS_APP", "System application is not exportable."),
                1101 => new Code(code, "COMADMIN_E_CANT_SUBSCRIBE_TO_COMPONENT", "Cannot subscribe to this component (the component might have been imported)."),
                1102 => new Code(code, "COMADMIN_E_EVENTCLASS_CANT_BE_SUBSCRIBER", "An event class cannot also be a subscriber component."),
                1103 => new Code(code, "COMADMIN_E_LIB_APP_PROXY_INCOMPATIBLE", "Library applications and application proxies are incompatible."),
                1104 => new Code(code, "COMADMIN_E_BASE_PARTITION_ONLY", "This function is valid for the base partition only."),
                1105 => new Code(code, "COMADMIN_E_START_APP_DISABLED", "You cannot start an application that has been disabled."),
                1111 => new Code(code, "COMADMIN_E_CAT_DUPLICATE_PARTITION_NAME", "The specified partition name is already in use on this computer."),
                1112 => new Code(code, "COMADMIN_E_CAT_INVALID_PARTITION_NAME", "The specified partition name is invalid. Check that the name contains at least one visible character."),
                1113 => new Code(code, "COMADMIN_E_CAT_PARTITION_IN_USE", "The partition cannot be deleted because it is the default partition for one or more users."),
                1114 => new Code(code, "COMADMIN_E_FILE_PARTITION_DUPLICATE_FILES", "The partition cannot be exported because one or more components in the partition have the same file name."),
                1115 => new Code(code, "COMADMIN_E_CAT_IMPORTED_COMPONENTS_NOT_ALLOWED", "Applications that contain one or more imported components cannot be installed into a nonbase partition."),
                1116 => new Code(code, "COMADMIN_E_AMBIGUOUS_APPLICATION_NAME", "The application name is not unique and cannot be resolved to an application ID."),
                1117 => new Code(code, "COMADMIN_E_AMBIGUOUS_PARTITION_NAME", "The partition name is not unique and cannot be resolved to a partition ID."),
                1138 => new Code(code, "COMADMIN_E_REGDB_NOTINITIALIZED", "The COM+ registry database has not been initialized."),
                1139 => new Code(code, "COMADMIN_E_REGDB_NOTOPEN", "The COM+ registry database is not open."),
                1140 => new Code(code, "COMADMIN_E_REGDB_SYSTEMERR", "The COM+ registry database detected a system error."),
                1141 => new Code(code, "COMADMIN_E_REGDB_ALREADYRUNNING", "The COM+ registry database is already running."),
                1152 => new Code(code, "COMADMIN_E_MIG_VERSIONNOTSUPPORTED", "This version of the COM+ registry database cannot be migrated."),
                1153 => new Code(code, "COMADMIN_E_MIG_SCHEMANOTFOUND", "The schema version to be migrated could not be found in the COM+ registry database."),
                1154 => new Code(code, "COMADMIN_E_CAT_BITNESSMISMATCH", "There was a type mismatch between binaries."),
                1155 => new Code(code, "COMADMIN_E_CAT_UNACCEPTABLEBITNESS", "A binary of unknown or invalid type was provided."),
                1156 => new Code(code, "COMADMIN_E_CAT_WRONGAPPBITNESS", "There was a type mismatch between a binary and an application."),
                1157 => new Code(code, "COMADMIN_E_CAT_PAUSE_RESUME_NOT_SUPPORTED", "The application cannot be paused or resumed."),
                1158 => new Code(code, "COMADMIN_E_CAT_SERVERFAULT", "The COM+ catalog server threw an exception during execution."),
                1536 => new Code(code, "COMQC_E_APPLICATION_NOT_QUEUED", "Only COM+ applications marked \"queued\" can be invoked using the \"queue\" moniker."),
                1537 => new Code(code, "COMQC_E_NO_QUEUEABLE_INTERFACES", "At least one interface must be marked \"queued\" to create a queued component instance with the \"queue\" moniker."),
                1538 => new Code(code, "COMQC_E_QUEUING_SERVICE_NOT_AVAILABLE", "Message Queuing is required for the requested operation and is not installed."),
                1539 => new Code(code, "COMQC_E_NO_IPERSISTSTREAM", "Unable to marshal an interface that does not support IPersistStream."),
                1540 => new Code(code, "COMQC_E_BAD_MESSAGE", "The message is improperly formatted or was damaged in transit."),
                1541 => new Code(code, "COMQC_E_UNAUTHENTICATED", "An unauthenticated message was received by an application that accepts only authenticated messages."),
                1542 => new Code(code, "COMQC_E_UNTRUSTED_ENQUEUER", "The message was requeued or moved by a user not in the QC Trusted User \"role\"."),
                1793 => new Code(code, "MSDTC_E_DUPLICATE_RESOURCE", "Cannot create a duplicate resource of type Distributed Transaction Coordinator."),
                2056 => new Code(code, "COMADMIN_E_OBJECT_PARENT_MISSING", "One of the objects being inserted or updated does not belong to a valid parent collection."),
                2057 => new Code(code, "COMADMIN_E_OBJECT_DOES_NOT_EXIST", "One of the specified objects cannot be found."),
                2058 => new Code(code, "COMADMIN_E_APP_NOT_RUNNING", "The specified application is not currently running."),
                2059 => new Code(code, "COMADMIN_E_INVALID_PARTITION", "The partitions specified are not valid."),
                2061 => new Code(code, "COMADMIN_E_SVCAPP_NOT_POOLABLE_OR_RECYCLABLE", "COM+ applications that run as Windows NT service cannot be pooled or recycled."),
                2062 => new Code(code, "COMADMIN_E_USER_IN_SET", "One or more users are already assigned to a local partition set."),
                2063 => new Code(code, "COMADMIN_E_CANTRECYCLELIBRARYAPPS", "Library applications cannot be recycled."),
                2065 => new Code(code, "COMADMIN_E_CANTRECYCLESERVICEAPPS", "Applications running as Windows NT services cannot be recycled."),
                2066 => new Code(code, "COMADMIN_E_PROCESSALREADYRECYCLED", "The process has already been recycled."),
                2067 => new Code(code, "COMADMIN_E_PAUSEDPROCESSMAYNOTBERECYCLED", "A paused process cannot be recycled."),
                2068 => new Code(code, "COMADMIN_E_CANTMAKEINPROCSERVICE", "Library applications cannot be Windows NT services."),
                2069 => new Code(code, "COMADMIN_E_PROGIDINUSEBYCLSID", "The ProgID provided to the copy operation is invalid. The ProgID is in use by another registered CLSID."),
                2070 => new Code(code, "COMADMIN_E_DEFAULT_PARTITION_NOT_IN_SET", "The partition specified as the default is not a member of the partition set."),
                2071 => new Code(code, "COMADMIN_E_RECYCLEDPROCESSMAYNOTBEPAUSED", "A recycled process cannot be paused."),
                2072 => new Code(code, "COMADMIN_E_PARTITION_ACCESSDENIED", "Access to the specified partition is denied."),
                2073 => new Code(code, "COMADMIN_E_PARTITION_MSI_ONLY", "Only application files (*.msi files) can be installed into partitions."),
                2074 => new Code(code, "COMADMIN_E_LEGACYCOMPS_NOT_ALLOWED_IN_1_0_FORMAT", "Applications containing one or more legacy components cannot be exported to 1.0 format."),
                2075 => new Code(code, "COMADMIN_E_LEGACYCOMPS_NOT_ALLOWED_IN_NONBASE_PARTITIONS", "Legacy components cannot exist in nonbase partitions."),
                2076 => new Code(code, "COMADMIN_E_COMP_MOVE_SOURCE", "A component cannot be moved (or copied) from the System Application, an application proxy, or a nonchangeable application."),
                2077 => new Code(code, "COMADMIN_E_COMP_MOVE_DEST", "A component cannot be moved (or copied) to the System Application, an application proxy or a nonchangeable application."),
                2078 => new Code(code, "COMADMIN_E_COMP_MOVE_PRIVATE", "A private component cannot be moved (or copied) to a library application or to the base partition."),
                2079 => new Code(code, "COMADMIN_E_BASEPARTITION_REQUIRED_IN_SET", "The Base Application Partition exists in all partition sets and cannot be removed."),
                2080 => new Code(code, "COMADMIN_E_CANNOT_ALIAS_EVENTCLASS", "Alas, Event Class components cannot be aliased."),
                2081 => new Code(code, "COMADMIN_E_PRIVATE_ACCESSDENIED", "Access is denied because the component is private."),
                2082 => new Code(code, "COMADMIN_E_SAFERINVALID", "The specified SAFER level is invalid."),
                2083 => new Code(code, "COMADMIN_E_REGISTRY_ACCESSDENIED", "The specified user cannot write to the system registry."),
                2084 => new Code(code, "COMADMIN_E_PARTITIONS_DISABLED", "COM+ partitions are currently disabled."),
                _ => Unknown(code),
            };
        }
    }
}
