namespace Elmah.Io.HResults.Facilities
{
    internal class FacilityUrtResolver : FacilityResolverBase
    {
        public FacilityUrtResolver() : base(19, "FACILITY_URT")
        {
        }

        internal override Code Resolve(bool failure, int code)
        {
            return code switch
            {
                4120 => new Code(code, "COR_E_ASSEMBLYEXPECTED"),
                4115 => new Code(code, "COR_E_TYPEUNLOADED"),
                5376 => new Code(code, "COR_E_EXCEPTION"),
                5377 => new Code(code, "COR_E_SYSTEM"),
                5378 => new Code(code, "COR_E_ARGUMENTOUTOFRANGE"),
                5379 => new Code(code, "COR_E_ARRAYTYPEMISMATCH"),
                5380 => new Code(code, "COR_E_CONTEXTMARSHAL"),
                5381 => new Code(code, "COR_E_TIMEOUT"),
                5382 => new Code(code, "COR_E_EXECUTIONENGINE"),
                5383 => new Code(code, "COR_E_FIELDACCESS"),
                5384 => new Code(code, "COR_E_INDEXOUTOFRANGE"),
                5385 => new Code(code, "COR_E_INVALIDOPERATION"),
                5386 => new Code(code, "COR_E_SECURITY"),
                5387 => new Code(code, "COR_E_REMOTING"),
                5388 => new Code(code, "COR_E_SERIALIZATION"),
                5389 => new Code(code, "COR_E_VERIFICATION"),
                5390 => new Code(code, "COR_E_SERVER"),
                5391 => new Code(code, "COR_E_SERVICEDCOMPONENT"),
                5392 => new Code(code, "COR_E_METHODACCESS"),
                5393 => new Code(code, "COR_E_MISSINGFIELD"),
                5394 => new Code(code, "COR_E_MISSINGMEMBER"),
                5395 => new Code(code, "COR_E_MISSINGMETHOD"),
                5396 => new Code(code, "COR_E_MULTICASTNOTSUPPORTED"),
                5397 => new Code(code, "COR_E_NOTSUPPORTED"),
                5398 => new Code(code, "COR_E_OVERFLOW"),
                5399 => new Code(code, "COR_E_RANK"),
                5400 => new Code(code, "COR_E_SYNCHRONIZATIONLOCK"),
                5401 => new Code(code, "COR_E_THREADINTERRUPTED"),
                5402 => new Code(code, "COR_E_MEMBERACCESS"),
                5408 => new Code(code, "COR_E_THREADSTATE"),
                5409 => new Code(code, "COR_E_THREADSTOP"),
                5410 => new Code(code, "COR_E_TYPELOAD"),
                5411 => new Code(code, "COR_E_ENTRYPOINTNOTFOUND"),
                5412 => new Code(code, "COR_E_DLLNOTFOUND"),
                5413 => new Code(code, "COR_E_THREADSTART"),
                5415 => new Code(code, "COR_E_INVALIDCOMOBJECT"),
                5416 => new Code(code, "COR_E_NOTFINITENUMBER"),
                5417 => new Code(code, "COR_E_DUPLICATEWAITOBJECT"),
                5419 => new Code(code, "COR_E_SEMAPHOREFULL"),
                5420 => new Code(code, "COR_E_WAITHANDLECANNOTBEOPENED"),
                5421 => new Code(code, "COR_E_ABANDONEDMUTEX"),
                5425 => new Code(code, "COR_E_INVALIDOLEVARIANTTYPE"),
                5426 => new Code(code, "COR_E_MISSINGMANIFESTRESOURCE"),
                5427 => new Code(code, "COR_E_SAFEARRAYTYPEMISMATCH"),
                5428 => new Code(code, "COR_E_TYPEINITIALIZATION"),
                5429 => new Code(code, "COR_E_MARSHALDIRECTIVE"),
                5430 => new Code(code, "COR_E_MISSINGSATELLITEASSEMBLY"),
                5431 => new Code(code, "COR_E_FORMAT"),
                5432 => new Code(code, "COR_E_SAFEARRAYRANKMISMATCH"),
                5433 => new Code(code, "COR_E_PLATFORMNOTSUPPORTED"),
                5434 => new Code(code, "COR_E_INVALIDPROGRAM"),
                5435 => new Code(code, "COR_E_OPERATIONCANCELED"),
                5437 => new Code(code, "COR_E_INSUFFICIENTMEMORY"),
                5438 => new Code(code, "COR_E_RUNTIMEWRAPPED"),
                5440 => new Code(code, "COR_E_DEVICESNOTSUPPORTED"),
                5441 => new Code(code, "COR_E_DATAMISALIGNED"),
                5495 => new Code(code, "COR_E_KEYNOTFOUND"),
                5632 => new Code(code, "COR_E_APPLICATION"),
                5633 => new Code(code, "COR_E_INVALIDFILTERCRITERIA"),
                5634 => new Code(code, "COR_E_REFLECTIONTYPELOAD"),
                5635 => new Code(code, "COR_E_TARGET"),
                5636 => new Code(code, "COR_E_TARGETINVOCATION"),
                5637 => new Code(code, "COR_E_CUSTOMATTRIBUTEFORMAT"),
                5664 => new Code(code, "COR_E_IO"),
                5665 => new Code(code, "COR_E_FILELOAD"),
                5666 => new Code(code, "COR_E_OBJECTDISPOSED"),
                5667 => new Code(code, "COR_E_FAILFAST"),
                5696 => new Code(code, "COR_E_HOSTPROTECTION"),
                5697 => new Code(code, "COR_E_ILLEGAL_REENTRANCY"),
                4167 => new Code(code, "FUSION_E_INVALID_NAME"),
                4359 => new Code(code, "CLDB_E_FILE_OLDVER"),
                5888 => new Code(code, "CLR_E_SHIM_RUNTIME"),
                5889 => new Code(code, "CLR_E_SHIM_RUNTIMEEXPORT"),
                _ => Unknown(code),
            };
        }
    }
}
