namespace Elmah.Io.HResults.Facilities
{
    internal class FacilitySetupapiResolver : FacilityResolverBase
    {
        public FacilitySetupapiResolver() : base(15, "FACILITY_SETUPAPI")
        {
        }

        internal override Code Resolve(bool failure, int code)
        {
            return code switch
            {
                0 => new Code(code, "SPAPI_E_EXPECTED_SECTION_NAME", "A non-empty line was encountered in the INF before the start of a section."),
                1 => new Code(code, "SPAPI_E_BAD_SECTION_NAME_LINE", "A section name marker in the information file (INF) is not complete or does not exist on a line by itself."),
                2 => new Code(code, "SPAPI_E_SECTION_NAME_TOO_LONG", "An INF section was encountered whose name exceeds the maximum section name length."),
                3 => new Code(code, "SPAPI_E_GENERAL_SYNTAX", "The syntax of the INF is invalid."),
                256 => new Code(code, "SPAPI_E_WRONG_INF_STYLE", "The style of the INF is different than what was requested."),
                257 => new Code(code, "SPAPI_E_SECTION_NOT_FOUND", "The required section was not found in the INF."),
                258 => new Code(code, "SPAPI_E_LINE_NOT_FOUND", "The required line was not found in the INF."),
                259 => new Code(code, "SPAPI_E_NO_BACKUP", "The files affected by the installation of this file queue have not been backed up for uninstall."),
                512 => new Code(code, "SPAPI_E_NO_ASSOCIATED_CLASS", "The INF or the device information set or element does not have an associated install class."),
                513 => new Code(code, "SPAPI_E_CLASS_MISMATCH", "The INF or the device information set or element does not match the specified install class."),
                514 => new Code(code, "SPAPI_E_DUPLICATE_FOUND", "An existing device was found that is a duplicate of the device being manually installed."),
                515 => new Code(code, "SPAPI_E_NO_DRIVER_SELECTED", "There is no driver selected for the device information set or element."),
                516 => new Code(code, "SPAPI_E_KEY_DOES_NOT_EXIST", "The requested device registry key does not exist."),
                517 => new Code(code, "SPAPI_E_INVALID_DEVINST_NAME", "The device instance name is invalid."),
                518 => new Code(code, "SPAPI_E_INVALID_CLASS", "The install class is not present or is invalid."),
                519 => new Code(code, "SPAPI_E_DEVINST_ALREADY_EXISTS", "The device instance cannot be created because it already exists."),
                520 => new Code(code, "SPAPI_E_DEVINFO_NOT_REGISTERED", "The operation cannot be performed on a device information element that has not been registered."),
                521 => new Code(code, "SPAPI_E_INVALID_REG_PROPERTY", "The device property code is invalid."),
                522 => new Code(code, "SPAPI_E_NO_INF", "The INF from which a driver list is to be built does not exist."),
                523 => new Code(code, "SPAPI_E_NO_SUCH_DEVINST", "The device instance does not exist in the hardware tree."),
                524 => new Code(code, "SPAPI_E_CANT_LOAD_CLASS_ICON", "The icon representing this install class cannot be loaded."),
                525 => new Code(code, "SPAPI_E_INVALID_CLASS_INSTALLER", "The class installer registry entry is invalid."),
                526 => new Code(code, "SPAPI_E_DI_DO_DEFAULT", "The class installer has indicated that the default action should be performed for this installation request."),
                527 => new Code(code, "SPAPI_E_DI_NOFILECOPY", "The operation does not require any files to be copied."),
                528 => new Code(code, "SPAPI_E_INVALID_HWPROFILE", "The specified hardware profile does not exist."),
                529 => new Code(code, "SPAPI_E_NO_DEVICE_SELECTED", "There is no device information element currently selected for this device information set."),
                530 => new Code(code, "SPAPI_E_DEVINFO_LIST_LOCKED", "The operation cannot be performed because the device information set is locked."),
                531 => new Code(code, "SPAPI_E_DEVINFO_DATA_LOCKED", "The operation cannot be performed because the device information element is locked."),
                532 => new Code(code, "SPAPI_E_DI_BAD_PATH", "The specified path does not contain any applicable device INFs."),
                533 => new Code(code, "SPAPI_E_NO_CLASSINSTALL_PARAMS", "No class installer parameters have been set for the device information set or element."),
                534 => new Code(code, "SPAPI_E_FILEQUEUE_LOCKED", "The operation cannot be performed because the file queue is locked."),
                535 => new Code(code, "SPAPI_E_BAD_SERVICE_INSTALLSECT", "A service installation section in this INF is invalid."),
                536 => new Code(code, "SPAPI_E_NO_CLASS_DRIVER_LIST", "There is no class driver list for the device information element."),
                537 => new Code(code, "SPAPI_E_NO_ASSOCIATED_SERVICE", "The installation failed because a function driver was not specified for this device instance."),
                538 => new Code(code, "SPAPI_E_NO_DEFAULT_DEVICE_INTERFACE", "There is presently no default device interface designated for this interface class."),
                539 => new Code(code, "SPAPI_E_DEVICE_INTERFACE_ACTIVE", "The operation cannot be performed because the device interface is currently active."),
                540 => new Code(code, "SPAPI_E_DEVICE_INTERFACE_REMOVED", "The operation cannot be performed because the device interface has been removed from the system."),
                541 => new Code(code, "SPAPI_E_BAD_INTERFACE_INSTALLSECT", "An interface installation section in this INF is invalid."),
                542 => new Code(code, "SPAPI_E_NO_SUCH_INTERFACE_CLASS", "This interface class does not exist in the system."),
                543 => new Code(code, "SPAPI_E_INVALID_REFERENCE_STRING", "The reference string supplied for this interface device is invalid."),
                544 => new Code(code, "SPAPI_E_INVALID_MACHINENAME", "The specified machine name does not conform to Universal Naming Convention (UNCs)."),
                545 => new Code(code, "SPAPI_E_REMOTE_COMM_FAILURE", "A general remote communication error occurred."),
                546 => new Code(code, "SPAPI_E_MACHINE_UNAVAILABLE", "The machine selected for remote communication is not available at this time."),
                547 => new Code(code, "SPAPI_E_NO_CONFIGMGR_SERVICES", "The Plug and Play service is not available on the remote machine."),
                548 => new Code(code, "SPAPI_E_INVALID_PROPPAGE_PROVIDER", "The property page provider registry entry is invalid."),
                549 => new Code(code, "SPAPI_E_NO_SUCH_DEVICE_INTERFACE", "The requested device interface is not present in the system."),
                550 => new Code(code, "SPAPI_E_DI_POSTPROCESSING_REQUIRED", "The device's co-installer has additional work to perform after installation is complete."),
                551 => new Code(code, "SPAPI_E_INVALID_COINSTALLER", "The device's co-installer is invalid."),
                552 => new Code(code, "SPAPI_E_NO_COMPAT_DRIVERS", "There are no compatible drivers for this device."),
                553 => new Code(code, "SPAPI_E_NO_DEVICE_ICON", "There is no icon that represents this device or device type."),
                554 => new Code(code, "SPAPI_E_INVALID_INF_LOGCONFIG", "A logical configuration specified in this INF is invalid."),
                555 => new Code(code, "SPAPI_E_DI_DONT_INSTALL", "The class installer has denied the request to install or upgrade this device."),
                556 => new Code(code, "SPAPI_E_INVALID_FILTER_DRIVER", "One of the filter drivers installed for this device is invalid."),
                557 => new Code(code, "SPAPI_E_NON_WINDOWS_NT_DRIVER", "The driver selected for this device does not support Windows XP operating system."),
                558 => new Code(code, "SPAPI_E_NON_WINDOWS_DRIVER", "The driver selected for this device does not support Windows."),
                559 => new Code(code, "SPAPI_E_NO_CATALOG_FOR_OEM_INF", "The third-party INF does not contain digital signature information."),
                560 => new Code(code, "SPAPI_E_DEVINSTALL_QUEUE_NONNATIVE", "An invalid attempt was made to use a device installation file queue for verification of digital signatures relative to other platforms."),
                561 => new Code(code, "SPAPI_E_NOT_DISABLEABLE", "The device cannot be disabled."),
                562 => new Code(code, "SPAPI_E_CANT_REMOVE_DEVINST", "The device could not be dynamically removed."),
                563 => new Code(code, "SPAPI_E_INVALID_TARGET", "Cannot copy to specified target."),
                564 => new Code(code, "SPAPI_E_DRIVER_NONNATIVE", "Driver is not intended for this platform."),
                565 => new Code(code, "SPAPI_E_IN_WOW64", "Operation not allowed in WOW64."),
                566 => new Code(code, "SPAPI_E_SET_SYSTEM_RESTORE_POINT", "The operation involving unsigned file copying was rolled back, so that a system restore point could be set."),
                567 => new Code(code, "SPAPI_E_INCORRECTLY_COPIED_INF", "An INF was copied into the Windows INF directory in an improper manner."),
                568 => new Code(code, "SPAPI_E_SCE_DISABLED", "The Security Configuration Editor (SCE) APIs have been disabled on this embedded product."),
                569 => new Code(code, "SPAPI_E_UNKNOWN_EXCEPTION", "An unknown exception was encountered."),
                570 => new Code(code, "SPAPI_E_PNP_REGISTRY_ERROR", "A problem was encountered when accessing the Plug and Play registry database."),
                571 => new Code(code, "SPAPI_E_REMOTE_REQUEST_UNSUPPORTED", "The requested operation is not supported for a remote machine."),
                572 => new Code(code, "SPAPI_E_NOT_AN_INSTALLED_OEM_INF", "The specified file is not an installed original equipment manufacturer (OEM) INF."),
                573 => new Code(code, "SPAPI_E_INF_IN_USE_BY_DEVICES", "One or more devices are presently installed using the specified INF."),
                574 => new Code(code, "SPAPI_E_DI_FUNCTION_OBSOLETE", "The requested device install operation is obsolete."),
                575 => new Code(code, "SPAPI_E_NO_AUTHENTICODE_CATALOG", "A file could not be verified because it does not have an associated catalog signed via Authenticode."),
                576 => new Code(code, "SPAPI_E_AUTHENTICODE_DISALLOWED", "Authenticode signature verification is not supported for the specified INF."),
                577 => new Code(code, "SPAPI_E_AUTHENTICODE_TRUSTED_PUBLISHER", "The INF was signed with an Authenticode catalog from a trusted publisher."),
                578 => new Code(code, "SPAPI_E_AUTHENTICODE_TRUST_NOT_ESTABLISHED", "The publisher of an Authenticode-signed catalog has not yet been established as trusted."),
                579 => new Code(code, "SPAPI_E_AUTHENTICODE_PUBLISHER_NOT_TRUSTED", "The publisher of an Authenticode-signed catalog was not established as trusted."),
                580 => new Code(code, "SPAPI_E_SIGNATURE_OSATTRIBUTE_MISMATCH", "The software was tested for compliance with Windows logo requirements on a different version of Windows and might not be compatible with this version."),
                581 => new Code(code, "SPAPI_E_ONLY_VALIDATE_VIA_AUTHENTICODE", "The file can be validated only by a catalog signed via Authenticode."),
                582 => new Code(code, "SPAPI_E_DEVICE_INSTALLER_NOT_READY", "One of the installers for this device cannot perform the installation at this time."),
                583 => new Code(code, "SPAPI_E_DRIVER_STORE_ADD_FAILED", "A problem was encountered while attempting to add the driver to the store."),
                584 => new Code(code, "SPAPI_E_DEVICE_INSTALL_BLOCKED", "The installation of this device is forbidden by system policy. Contact your system administrator."),
                585 => new Code(code, "SPAPI_E_DRIVER_INSTALL_BLOCKED", "The installation of this driver is forbidden by system policy. Contact your system administrator."),
                586 => new Code(code, "SPAPI_E_WRONG_INF_TYPE", "The specified INF is the wrong type for this operation."),
                587 => new Code(code, "SPAPI_E_FILE_HASH_NOT_IN_CATALOG", "The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering."),
                588 => new Code(code, "SPAPI_E_DRIVER_STORE_DELETE_FAILED", "A problem was encountered while attempting to delete the driver from the store."),
                768 => new Code(code, "SPAPI_E_UNRECOVERABLE_STACK_OVERFLOW", "An unrecoverable stack overflow was encountered."),
                4096 => new Code(code, "SPAPI_E_ERROR_NOT_INSTALLED", "No installed components were detected."),
                _ => Unknown(code),
            };
        }
    }
}
