namespace Elmah.Io.HResults.Facilities
{
    internal class FacilityRpcResolver : FacilityResolverBase
    {
        public FacilityRpcResolver() : base(1, "FACILITY_RPC")
        {
        }

        internal override Code Resolve(bool failure, int code)
        {
            return code switch
            {
                1 => new Code(code, "RPC_E_CALL_REJECTED", "Call was rejected by callee."),
                2 => new Code(code, "RPC_E_CALL_CANCELED", "Call was canceled by the message filter."),
                3 => new Code(code, "RPC_E_CANTPOST_INSENDCALL", "The caller is dispatching an intertask SendMessage call and cannot call out via PostMessage."),
                4 => new Code(code, "RPC_E_CANTCALLOUT_INASYNCCALL", "The caller is dispatching an asynchronous call and cannot make an outgoing call on behalf of this call."),
                5 => new Code(code, "RPC_E_CANTCALLOUT_INEXTERNALCALL", "It is illegal to call out while inside message filter."),
                6 => new Code(code, "RPC_E_CONNECTION_TERMINATED", "The connection terminated or is in a bogus state and can no longer be used. Other connections are still valid."),
                7 => new Code(code, "RPC_E_SERVER_DIED", "The callee (the server, not the server application) is not available and disappeared; all connections are invalid. The call might have executed."),
                8 => new Code(code, "RPC_E_CLIENT_DIED", "The caller (client) disappeared while the callee (server) was processing a call."),
                9 => new Code(code, "RPC_E_INVALID_DATAPACKET", "The data packet with the marshaled parameter data is incorrect."),
                10 => new Code(code, "RPC_E_CANTTRANSMIT_CALL", "The call was not transmitted properly; the message queue was full and was not emptied after yielding."),
                11 => new Code(code, "RPC_E_CLIENT_CANTMARSHAL_DATA", "The client RPC caller cannot marshal the parameter data due to errors (such as low memory)."),
                12 => new Code(code, "RPC_E_CLIENT_CANTUNMARSHAL_DATA", "The client RPC caller cannot unmarshal the return data due to errors (such as low memory)."),
                13 => new Code(code, "RPC_E_SERVER_CANTMARSHAL_DATA", "The server RPC callee cannot marshal the return data due to errors (such as low memory)."),
                14 => new Code(code, "RPC_E_SERVER_CANTUNMARSHAL_DATA", "The server RPC callee cannot unmarshal the parameter data due to errors (such as low memory)."),
                15 => new Code(code, "RPC_E_INVALID_DATA", "Received data is invalid. The data might be server or client data."),
                16 => new Code(code, "RPC_E_INVALID_PARAMETER", "A particular parameter is invalid and cannot be (un)marshaled."),
                17 => new Code(code, "RPC_E_CANTCALLOUT_AGAIN", "There is no second outgoing call on same channel in DDE conversation."),
                18 => new Code(code, "RPC_E_SERVER_DIED_DNE", "The callee (the server, not the server application) is not available and disappeared; all connections are invalid. The call did not execute."),
                256 => new Code(code, "RPC_E_SYS_CALL_FAILED", "System call failed."),
                257 => new Code(code, "RPC_E_OUT_OF_RESOURCES", "Could not allocate some required resource (such as memory or events)"),
                258 => new Code(code, "RPC_E_ATTEMPTED_MULTITHREAD", "Attempted to make calls on more than one thread in single-threaded mode."),
                259 => new Code(code, "RPC_E_NOT_REGISTERED", "The requested interface is not registered on the server object."),
                260 => new Code(code, "RPC_E_FAULT", "RPC could not call the server or could not return the results of calling the server."),
                261 => new Code(code, "RPC_E_SERVERFAULT", "The server threw an exception."),
                262 => new Code(code, "RPC_E_CHANGED_MODE", "Cannot change thread mode after it is set."),
                263 => new Code(code, "RPC_E_INVALIDMETHOD", "The method called does not exist on the server."),
                264 => new Code(code, "RPC_E_DISCONNECTED", "The object invoked has disconnected from its clients."),
                265 => new Code(code, "RPC_E_RETRY", "The object invoked chose not to process the call now. Try again later."),
                266 => new Code(code, "RPC_E_SERVERCALL_RETRYLATER", "The message filter indicated that the application is busy."),
                267 => new Code(code, "RPC_E_SERVERCALL_REJECTED", "The message filter rejected the call."),
                268 => new Code(code, "RPC_E_INVALID_CALLDATA", "A call control interface was called with invalid data."),
                269 => new Code(code, "RPC_E_CANTCALLOUT_ININPUTSYNCCALL", "An outgoing call cannot be made because the application is dispatching an input-synchronous call."),
                270 => new Code(code, "RPC_E_WRONG_THREAD", "The application called an interface that was marshaled for a different thread."),
                271 => new Code(code, "RPC_E_THREAD_NOT_INIT", "CoInitialize has not been called on the current thread."),
                272 => new Code(code, "RPC_E_VERSION_MISMATCH", "The version of OLE on the client and server machines does not match."),
                273 => new Code(code, "RPC_E_INVALID_HEADER", "OLE received a packet with an invalid header."),
                274 => new Code(code, "RPC_E_INVALID_EXTENSION", "OLE received a packet with an invalid extension."),
                275 => new Code(code, "RPC_E_INVALID_IPID", "The requested object or interface does not exist."),
                276 => new Code(code, "RPC_E_INVALID_OBJECT", "The requested object does not exist."),
                277 => new Code(code, "RPC_S_CALLPENDING", "OLE has sent a request and is waiting for a reply."),
                278 => new Code(code, "RPC_S_WAITONTIMER", "OLE is waiting before retrying a request."),
                279 => new Code(code, "RPC_E_CALL_COMPLETE", "Call context cannot be accessed after call completed."),
                280 => new Code(code, "RPC_E_UNSECURE_CALL", "Impersonate on unsecure calls is not supported."),
                281 => new Code(code, "RPC_E_TOO_LATE", "Security must be initialized before any interfaces are marshaled or unmarshaled. It cannot be changed after initialized."),
                282 => new Code(code, "RPC_E_NO_GOOD_SECURITY_PACKAGES", "No security packages are installed on this machine, the user is not logged on, or there are no compatible security packages between the client and server."),
                283 => new Code(code, "RPC_E_ACCESS_DENIED", "Access is denied."),
                284 => new Code(code, "RPC_E_REMOTE_DISABLED", "Remote calls are not allowed for this process."),
                285 => new Code(code, "RPC_E_INVALID_OBJREF", "The marshaled interface data packet (OBJREF) has an invalid or unknown format."),
                286 => new Code(code, "RPC_E_NO_CONTEXT", "No context is associated with this call. This happens for some custom marshaled calls and on the client side of the call."),
                287 => new Code(code, "RPC_E_TIMEOUT", "This operation returned because the time-out period expired."),
                288 => new Code(code, "RPC_E_NO_SYNC", "There are no synchronize objects to wait on."),
                289 => new Code(code, "RPC_E_FULLSIC_REQUIRED", "Full subject issuer chain Secure Sockets Layer (SSL) principal name expected from the server."),
                290 => new Code(code, "RPC_E_INVALID_STD_NAME", "Principal name is not a valid Microsoft standard (msstd) name."),
                291 => new Code(code, "CO_E_FAILEDTOIMPERSONATE", "Unable to impersonate DCOM client."),
                292 => new Code(code, "CO_E_FAILEDTOGETSECCTX", "Unable to obtain server's security context."),
                293 => new Code(code, "CO_E_FAILEDTOOPENTHREADTOKEN", "Unable to open the access token of the current thread."),
                294 => new Code(code, "CO_E_FAILEDTOGETTOKENINFO", "Unable to obtain user information from an access token."),
                295 => new Code(code, "CO_E_TRUSTEEDOESNTMATCHCLIENT", "The client who called IAccessControl::IsAccessPermitted was not the trustee provided to the method."),
                296 => new Code(code, "CO_E_FAILEDTOQUERYCLIENTBLANKET", "Unable to obtain the client's security blanket."),
                297 => new Code(code, "CO_E_FAILEDTOSETDACL", "Unable to set a discretionary access control list (ACL) into a security descriptor."),
                298 => new Code(code, "CO_E_ACCESSCHECKFAILED", "The system function AccessCheck returned false."),
                299 => new Code(code, "CO_E_NETACCESSAPIFAILED", "Either NetAccessDel or NetAccessAdd returned an error code."),
                300 => new Code(code, "CO_E_WRONGTRUSTEENAMESYNTAX", "One of the trustee strings provided by the user did not conform to the <Domain>\\<Name> syntax and it was not the *\" string\"."),
                301 => new Code(code, "CO_E_INVALIDSID", "One of the security identifiers provided by the user was invalid."),
                302 => new Code(code, "CO_E_CONVERSIONFAILED", "Unable to convert a wide character trustee string to a multiple-byte trustee string."),
                303 => new Code(code, "CO_E_NOMATCHINGSIDFOUND", "Unable to find a security identifier that corresponds to a trustee string provided by the user."),
                304 => new Code(code, "CO_E_LOOKUPACCSIDFAILED", "The system function LookupAccountSID failed."),
                305 => new Code(code, "CO_E_NOMATCHINGNAMEFOUND", "Unable to find a trustee name that corresponds to a security identifier provided by the user."),
                306 => new Code(code, "CO_E_LOOKUPACCNAMEFAILED", "The system function LookupAccountName failed."),
                307 => new Code(code, "CO_E_SETSERLHNDLFAILED", "Unable to set or reset a serialization handle."),
                308 => new Code(code, "CO_E_FAILEDTOGETWINDIR", "Unable to obtain the Windows directory."),
                309 => new Code(code, "CO_E_PATHTOOLONG", "Path too long."),
                310 => new Code(code, "CO_E_FAILEDTOGENUUID", "Unable to generate a UUID."),
                311 => new Code(code, "CO_E_FAILEDTOCREATEFILE", "Unable to create file."),
                312 => new Code(code, "CO_E_FAILEDTOCLOSEHANDLE", "Unable to close a serialization handle or a file handle."),
                313 => new Code(code, "CO_E_EXCEEDSYSACLLIMIT", "The number of access control entries (ACEs) in an ACL exceeds the system limit."),
                314 => new Code(code, "CO_E_ACESINWRONGORDER", "Not all the DENY_ACCESS ACEs are arranged in front of the GRANT_ACCESS ACEs in the stream."),
                315 => new Code(code, "CO_E_INCOMPATIBLESTREAMVERSION", "The version of ACL format in the stream is not supported by this implementation of IAccessControl."),
                316 => new Code(code, "CO_E_FAILEDTOOPENPROCESSTOKEN", "Unable to open the access token of the server process."),
                317 => new Code(code, "CO_E_DECODEFAILED", "Unable to decode the ACL in the stream provided by the user."),
                319 => new Code(code, "CO_E_ACNOTINITIALIZED", "The COM IAccessControl object is not initialized."),
                320 => new Code(code, "CO_E_CANCEL_DISABLED", "Call Cancellation is disabled."),
                65535 => new Code(code, "RPC_E_UNEXPECTED", "An internal error occurred."),
                _ => Unknown(code),
            };
        }
    }
}
