using System;
using System.Collections.Generic;
using System.Text;

namespace Elmah.Io.HResults.Facilities
{
    // Sources:
    // - https://learn.microsoft.com/en-us/troubleshoot/developer/dotnet/framework/general/wpf-render-thread-failures
    // - https://github.com/microsoft/pyright/blob/8b02aa84ec916697e76d5ee69299a89d555ec98c/packages/pyright-internal/typeshed-fallback/stubs/pywin32/win32/lib/winerror.pyi
    // - https://windows-hexerror.linestarve.com/browse/facilities/2200

    internal class FacilityWincodecDwriteDwmResolver : FacilityResolverBase
    {
        public FacilityWincodecDwriteDwmResolver() : base(2200, "FACILITY_WINCODEC_DWRITE_DWM")
        {
        }

        internal override Code Resolve(bool failure, int code)
        {
            return code switch
            {
                20480 => new Code(code, "DWRITE_E_FILEFORMAT", "Indicates an error in an input file such as a font file."),
                20481 => new Code(code, "DWRITE_E_UNEXPECTED", "Indicates an error originating in DirectWrite code, which is not expected to occur but is safe to recover from."),
                20482 => new Code(code, "DWRITE_E_NOFONT", "Indicates the specified font does not exist."),
                20483 => new Code(code, "DWRITE_E_FILENOTFOUND", "A font file could not be opened because the file, directory, network location, drive, or other storage location does not exist or is unavailable."),
                20484 => new Code(code, "DWRITE_E_FILEACCESS", "A font file exists but could not be opened due to access denied, sharing violation, or similar error."),
                20485 => new Code(code, "DWRITE_E_FONTCOLLECTIONOBSOLETE", "A font collection is obsolete due to changes in the system."),
                20486 => new Code(code, "DWRITE_E_ALREADYREGISTERED", "The given interface is already registered."),
                20487 => new Code(code, "DWRITE_E_CACHEFORMAT", "The font cache contains invalid data."),
                20488 => new Code(code, "DWRITE_E_CACHEVERSION", "A font cache file corresponds to a different version of DirectWrite."),
                20489 => new Code(code, "DWRITE_E_UNSUPPORTEDOPERATION", "The operation is not supported for this type of font."),
                20490 => new Code(code, "DWRITE_E_TEXTRENDERERINCOMPATIBLE", "The version of the text renderer interface is not compatible."),
                20491 => new Code(code, "DWRITE_E_FLOWDIRECTIONCONFLICTS", "The flow direction conflicts with the reading direction. They must be perpendicular to each other."),
                20492 => new Code(code, "DWRITE_E_NOCOLOR", "The font or glyph run does not contain any colored glyphs."),
                12036 => new Code(code, "WINCODEC_ERR_WRONGSTATE", "The codec is in the wrong state."),
                12037 => new Code(code, "WINCODEC_ERR_VALUEOUTOFRANGE", "The value is out of range."),
                12039 => new Code(code, "WINCODEC_ERR_UNKNOWNIMAGEFORMAT", "The image format is unknown."),
                12043 => new Code(code, "WINCODEC_ERR_UNSUPPORTEDVERSION", "The SDK version is unsupported."),
                12044 => new Code(code, "WINCODEC_ERR_NOTINITIALIZED", "The component is not initialized."),
                12045 => new Code(code, "WINCODEC_ERR_ALREADYLOCKED", "There is already an outstanding read or write lock."),
                12096 => new Code(code, "WINCODEC_ERR_PROPERTYNOTFOUND", "The specified bitmap property cannot be found."),
                12097 => new Code(code, "WINCODEC_ERR_PROPERTYNOTSUPPORTED", "The bitmap codec does not support the bitmap property."),
                12098 => new Code(code, "WINCODEC_ERR_PROPERTYSIZE", "The bitmap property size is invalid."),
                12099 => new Code(code, "WINCODEC_ERR_CODECPRESENT", "An unknown error has occurred."),
                12100 => new Code(code, "WINCODEC_ERR_CODECNOTHUMBNAIL", "The bitmap codec does not support a thumbnail."),
                12101 => new Code(code, "WINCODEC_ERR_PALETTEUNAVAILABLE", "The bitmap palette is unavailable."),
                12102 => new Code(code, "WINCODEC_ERR_CODECTOOMANYSCANLINES", "Too many scanlines were requested."),
                12104 => new Code(code, "WINCODEC_ERR_INTERNALERROR", "An internal error occurred."),
                12105 => new Code(code, "WINCODEC_ERR_SOURCERECTDOESNOTMATCHDIMENSIONS", "The bitmap bounds do not match the bitmap dimensions."),
                12112 => new Code(code, "WINCODEC_ERR_COMPONENTNOTFOUND", "The component cannot be found."),
                12113 => new Code(code, "WINCODEC_ERR_IMAGESIZEOUTOFRANGE", "The bitmap size is outside the valid range."),
                12114 => new Code(code, "WINCODEC_ERR_TOOMUCHMETADATA", "There is too much metadata to be written to the bitmap."),
                12128 => new Code(code, "WINCODEC_ERR_BADIMAGE", "The image is unrecognized."),
                12129 => new Code(code, "WINCODEC_ERR_BADHEADER", "The image header is unrecognized."),
                12130 => new Code(code, "WINCODEC_ERR_FRAMEMISSING", "The bitmap frame is missing."),
                12131 => new Code(code, "WINCODEC_ERR_BADMETADATAHEADER", "The image metadata header is unrecognized."),
                12144 => new Code(code, "WINCODEC_ERR_BADSTREAMDATA", "The stream data is unrecognized."),
                12145 => new Code(code, "WINCODEC_ERR_STREAMWRITE", "Failed to write to the stream."),
                12146 => new Code(code, "WINCODEC_ERR_STREAMREAD", "Failed to read from the stream."),
                12147 => new Code(code, "WINCODEC_ERR_STREAMNOTAVAILABLE", "The stream is not available."),
                12160 => new Code(code, "WINCODEC_ERR_UNSUPPORTEDPIXELFORMAT", "The bitmap pixel format is unsupported."),
                12161 => new Code(code, "WINCODEC_ERR_UNSUPPORTEDOPERATION", "The operation is unsupported."),
                12170 => new Code(code, "WINCODEC_ERR_INVALIDREGISTRATION", "The component registration is invalid."),
                12171 => new Code(code, "WINCODEC_ERR_COMPONENTINITIALIZEFAILURE", "The component initialization has failed."),
                12172 => new Code(code, "WINCODEC_ERR_INSUFFICIENTBUFFER", "The buffer allocated is insufficient."),
                12173 => new Code(code, "WINCODEC_ERR_DUPLICATEMETADATAPRESENT", "Duplicate metadata is present."),
                12174 => new Code(code, "WINCODEC_ERR_PROPERTYUNEXPECTEDTYPE", "The bitmap property type is unexpected."),
                12175 => new Code(code, "WINCODEC_ERR_UNEXPECTEDSIZE", "The size is unexpected."),
                12176 => new Code(code, "WINCODEC_ERR_INVALIDQUERYREQUEST", "The property query is invalid."),
                12177 => new Code(code, "WINCODEC_ERR_UNEXPECTEDMETADATATYPE", "The metadata type is unexpected."),
                12178 => new Code(code, "WINCODEC_ERR_REQUESTONLYVALIDATMETADATAROOT", "The specified bitmap property is only valid at root level."),
                12179 => new Code(code, "WINCODEC_ERR_INVALIDQUERYCHARACTER", "The query string contains an invalid character."),
                12180 => new Code(code, "WINCODEC_ERR_WIN32ERROR", "Windows Codecs received an error from the Win32 system."),
                12181 => new Code(code, "WINCODEC_ERR_INVALIDPROGRESSIVELEVEL", "The requested level of detail is not present."),
                12182 => new Code(code, "WINCODEC_ERR_INVALIDJPEGSCANINDEX", "The scan index is invalid."),
                1 => new Code(code, "MILERR_OBJECTBUSY"),
                2 => new Code(code, "MILERR_INSUFFICIENTBUFFER"),
                3 => new Code(code, "MILERR_WIN32ERROR"),
                4 => new Code(code, "MILERR_SCANNER_FAILED"),
                5 => new Code(code, "MILERR_SCREENACCESSDENIED"),
                6 => new Code(code, "MILERR_DISPLAYSTATEINVALID"),
                7 => new Code(code, "MILERR_NONINVERTIBLEMATRIX"),
                8 => new Code(code, "MILERR_ZEROVECTOR"),
                9 => new Code(code, "MILERR_TERMINATED"),
                10 => new Code(code, "MILERR_BADNUMBER"),
                128 => new Code(code, "MILERR_INTERNALERROR", "An internal error (MIL bug) occurred. On checked builds, an assert would be raised."),
                132 => new Code(code, "MILERR_DISPLAYFORMATNOTSUPPORTED", "The display format we need to render is not supported by the hardware device."),
                133 => new Code(code, "MILERR_INVALIDCALL", "A call to this method is invalid."),
                134 => new Code(code, "MILERR_ALREADYLOCKED", "Lock attempted on an already locked object."),
                135 => new Code(code, "MILERR_NOTLOCKED", "Unlock attempted on an unlocked object."),
                136 => new Code(code, "MILERR_DEVICECANNOTRENDERTEXT", "No algorithm avaliable to render text with this device"),
                137 => new Code(code, "MILERR_GLYPHBITMAPMISSED", "Some glyph bitmaps, required for glyph run rendering, are not contained in glyph cache."),
                138 => new Code(code, "MILERR_MALFORMEDGLYPHCACHE", "Some glyph bitmaps in glyph cache are unexpectedly big."),
                139 => new Code(code, "MILERR_GENERIC_IGNORE", "Marker error for known Win32 errors that are currently being ignored by the compositor. This is to avoid returning S_OK when an error has occurred, but still unwind the stack in the correct location."),
                140 => new Code(code, "MILERR_MALFORMED_GUIDELINE_DATA", "Guideline coordinates are not sorted properly or contain NaNs."),
                141 => new Code(code, "MILERR_NO_HARDWARE_DEVICE", "No HW rendering device is available for this operation."),
                142 => new Code(code, "MILERR_NEED_RECREATE_AND_PRESENT", "There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present. There are two known case for this: 1) D3D Driver Internal error 2) D3D E_FAIL 2a) Unknown root cause b) When resizing too quickly for DWM and D3D stay in sync"),
                143 => new Code(code, "MILERR_ALREADY_INITIALIZED", "The object has already been initialized."),
                144 => new Code(code, "MILERR_MISMATCHED_SIZE", "The size of the object does not match the expected size."),
                145 => new Code(code, "MILERR_NO_REDIRECTION_SURFACE_AVAILABLE", "No Redirection surface available."),
                146 => new Code(code, "MILERR_REMOTING_NOT_SUPPORTED", "Remoting of this content is not supported."),
                147 => new Code(code, "MILERR_QUEUED_PRESENT_NOT_SUPPORTED", "Queued Presents are not supported."),
                148 => new Code(code, "MILERR_NOT_QUEUING_PRESENTS", "Queued Presents are not being used."),
                149 => new Code(code, "MILERR_NO_REDIRECTION_SURFACE_RETRY_LATER", "No redirection surface was available. Caller should retry the call."),
                150 => new Code(code, "MILERR_TOOMANYSHADERELEMNTS", "Shader construction failed because it was too complex."),
                151 => new Code(code, "MILERR_MROW_READLOCK_FAILED", "MROW attempt to get a read lock failed."),
                152 => new Code(code, "MILERR_MROW_UPDATE_FAILED", "MROW attempt to update the data failed because another update was outstanding."),
                153 => new Code(code, "MILERR_SHADER_COMPILE_FAILED", "Shader compilation failed."),
                154 => new Code(code, "MILERR_MAX_TEXTURE_SIZE_EXCEEDED", "Requested DX redirection surface size exceeded maximum texture size."),
                155 => new Code(code, "MILERR_QPC_TIME_WENT_BACKWARD", "QueryPerformanceCounter returned a time in the past."),
                157 => new Code(code, "MILERR_DXGI_ENUMERATION_OUT_OF_SYNC", "Primary Display device returned an invalid refresh rate."),
                158 => new Code(code, "MILERR_ADAPTER_NOT_FOUND", "DWM can not find the adapter specified by the LUID."),
                159 => new Code(code, "MILERR_COLORSPACE_NOT_SUPPORTED", "The requested bitmap color space is not supported."),
                160 => new Code(code, "MILERR_PREFILTER_NOT_SUPPORTED", "The requested bitmap pre-filtering state is not supported."),
                161 => new Code(code, "MILERR_DISPLAYID_ACCESS_DENIED", "Access is denied to the requested bitmap for the specified display id."),
                1024 => new Code(code, "UCEERR_INVALIDPACKETHEADER"),
                1025 => new Code(code, "UCEERR_UNKNOWNPACKET"),
                1026 => new Code(code, "UCEERR_ILLEGALPACKET"),
                1027 => new Code(code, "UCEERR_MALFORMEDPACKET"),
                1028 => new Code(code, "UCEERR_ILLEGALHANDLE"),
                1029 => new Code(code, "UCEERR_HANDLELOOKUPFAILED"),
                1030 => new Code(code, "UCEERR_RENDERTHREADFAILURE"),
                1031 => new Code(code, "UCEERR_CTXSTACKFRSTTARGETNULL"),
                1032 => new Code(code, "UCEERR_CONNECTIONIDLOOKUPFAILED"),
                1033 => new Code(code, "UCEERR_BLOCKSFULL"),
                1034 => new Code(code, "UCEERR_MEMORYFAILURE"),
                1035 => new Code(code, "UCEERR_PACKETRECORDOUTOFRANGE"),
                1036 => new Code(code, "UCEERR_ILLEGALRECORDTYPE"),
                1037 => new Code(code, "UCEERR_OUTOFHANDLES"),
                1038 => new Code(code, "UCEERR_UNCHANGABLE_UPDATE_ATTEMPTED"),
                1039 => new Code(code, "UCEERR_NO_MULTIPLE_WORKER_THREADS"),
                1040 => new Code(code, "UCEERR_REMOTINGNOTSUPPORTED"),
                1041 => new Code(code, "UCEERR_MISSINGENDCOMMAND"),
                1042 => new Code(code, "UCEERR_MISSINGBEGINCOMMAND"),
                1043 => new Code(code, "UCEERR_CHANNELSYNCTIMEDOUT"),
                1044 => new Code(code, "UCEERR_CHANNELSYNCABANDONED"),
                1045 => new Code(code, "UCEERR_UNSUPPORTEDTRANSPORTVERSION"),
                1046 => new Code(code, "UCEERR_TRANSPORTUNAVAILABLE"),
                1047 => new Code(code, "UCEERR_FEEDBACK_UNSUPPORTED"),
                1048 => new Code(code, "UCEERR_COMMANDTRANSPORTDENIED"),
                1049 => new Code(code, "UCEERR_GRAPHICSSTREAMUNAVAILABLE"),
                1056 => new Code(code, "UCEERR_GRAPHICSSTREAMALREADYOPEN"),
                1057 => new Code(code, "UCEERR_TRANSPORTDISCONNECTED"),
                1058 => new Code(code, "UCEERR_TRANSPORTOVERLOADED"),
                1059 => new Code(code, "UCEERR_PARTITION_ZOMBIED"),
                1280 => new Code(code, "MILAVERR_NOCLOCK"),
                1281 => new Code(code, "MILAVERR_NOMEDIATYPE"),
                1282 => new Code(code, "MILAVERR_NOVIDEOMIXER"),
                1283 => new Code(code, "MILAVERR_NOVIDEOPRESENTER"),
                1284 => new Code(code, "MILAVERR_NOREADYFRAMES"),
                1285 => new Code(code, "MILAVERR_MODULENOTLOADED"),
                1286 => new Code(code, "MILAVERR_WMPFACTORYNOTREGISTERED"),
                1287 => new Code(code, "MILAVERR_INVALIDWMPVERSION"),
                1288 => new Code(code, "MILAVERR_INSUFFICIENTVIDEORESOURCES"),
                1289 => new Code(code, "MILAVERR_VIDEOACCELERATIONNOTAVAILABLE"),
                1290 => new Code(code, "MILAVERR_REQUESTEDTEXTURETOOBIG"),
                1291 => new Code(code, "MILAVERR_SEEKFAILED"),
                1292 => new Code(code, "MILAVERR_UNEXPECTEDWMPFAILURE"),
                1293 => new Code(code, "MILAVERR_MEDIAPLAYERCLOSED"),
                1294 => new Code(code, "MILAVERR_UNKNOWNHARDWAREERROR"),
                1550 => new Code(code, "MILEFFECTSERR_UNKNOWNPROPERTY"),
                1551 => new Code(code, "MILEFFECTSERR_EFFECTNOTPARTOFGROUP"),
                1552 => new Code(code, "MILEFFECTSERR_NOINPUTSOURCEATTACHED"),
                1553 => new Code(code, "MILEFFECTSERR_CONNECTORNOTCONNECTED"),
                1554 => new Code(code, "MILEFFECTSERR_CONNECTORNOTASSOCIATEDWITHEFFECT"),
                1555 => new Code(code, "MILEFFECTSERR_RESERVED"),
                1556 => new Code(code, "MILEFFECTSERR_CYCLEDETECTED"),
                1557 => new Code(code, "MILEFFECTSERR_EFFECTINMORETHANONEGRAPH"),
                1558 => new Code(code, "MILEFFECTSERR_EFFECTALREADYINAGRAPH"),
                1559 => new Code(code, "MILEFFECTSERR_EFFECTHASNOCHILDREN"),
                1560 => new Code(code, "MILEFFECTSERR_ALREADYATTACHEDTOLISTENER"),
                1561 => new Code(code, "MILEFFECTSERR_NOTAFFINETRANSFORM"),
                1562 => new Code(code, "MILEFFECTSERR_EMPTYBOUNDS"),
                1563 => new Code(code, "MILEFFECTSERR_OUTPUTSIZETOOLARGE"),
                1792 => new Code(code, "DWMERR_STATE_TRANSITION_FAILED"),
                1793 => new Code(code, "DWMERR_THEME_FAILED"),
                1794 => new Code(code, "DWMERR_CATASTROPHIC_FAILURE"),
                2048 => new Code(code, "DCOMPOSITION_ERROR_WINDOW_ALREADY_COMPOSED"),
                2049 => new Code(code, "DCOMPOSITION_ERROR_SURFACE_BEING_RENDERED"),
                2050 => new Code(code, "DCOMPOSITION_ERROR_SURFACE_NOT_BEING_RENDERED"),
                _ => Unknown(code),
            };
        }
    }
}
